// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjXlYBP5vVZjQIUMkpxDp4I9sQykPaBI',
    appId: '1:75068223096:web:924444fe850b02d346878d',
    messagingSenderId: '75068223096',
    projectId: 'food-now-7d71c',
    authDomain: 'food-now-7d71c.firebaseapp.com',
    storageBucket: 'food-now-7d71c.firebasestorage.app',
    measurementId: 'G-9MZFEBSQ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSEiolieRqA9hvXgz9YQnOu0v0zWUH5U',
    appId: '1:75068223096:android:f7719aff23ec69e946878d',
    messagingSenderId: '75068223096',
    projectId: 'food-now-7d71c',
    storageBucket: 'food-now-7d71c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEpAa3-qPs_szFX4VqRUWn7pzj6cfJ1Y',
    appId: '1:75068223096:ios:062070eaa23d576346878d',
    messagingSenderId: '75068223096',
    projectId: 'food-now-7d71c',
    storageBucket: 'food-now-7d71c.firebasestorage.app',
    iosBundleId: 'com.example.foodNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEpAa3-qPs_szFX4VqRUWn7pzj6cfJ1Y',
    appId: '1:75068223096:ios:062070eaa23d576346878d',
    messagingSenderId: '75068223096',
    projectId: 'food-now-7d71c',
    storageBucket: 'food-now-7d71c.firebasestorage.app',
    iosBundleId: 'com.example.foodNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjjXlYBP5vVZjQIUMkpxDp4I9sQykPaBI',
    appId: '1:75068223096:web:59781d9ebbeff50346878d',
    messagingSenderId: '75068223096',
    projectId: 'food-now-7d71c',
    authDomain: 'food-now-7d71c.firebaseapp.com',
    storageBucket: 'food-now-7d71c.firebasestorage.app',
    measurementId: 'G-JXKCQREJQP',
  );
}
